name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create deployment
        id: deployment
        uses: octokit/request-action@v2
        with:
          route: POST /repos/:owner/:repo/deployments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          ref: ${{ github.ref }}
          environment: production
          description: Deploy to Vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod

      - name: Update deployment status
        if: success()
        uses: octokit/request-action@v2
        with:
          route: POST /repos/:owner/:repo/deployments/${{ steps.deployment.outputs.id }}/statuses
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          state: success
          environment: production
          log_url: ${{ steps.vercel.outputs.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
