name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod

      - name: Create GitHub Deployment
        id: create_deployment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          environment: production
          description: Deploy to Vercel
          auto_merge: false

      - name: Update deployment status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository_owner }}/${{ github.repository }}/deployments/${{ steps.create_deployment.outputs.deployment_id }}/statuses
          state: success
          environment: production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
